library(testthat)
library(microclim)
source("test.R")

test_that("mc_read_from_csv", {
    data <- mc_read_from_csv("data/TOMST/files_table.csv")
    test_standard_data_format(data)
    expect_equal(length(data), 3)
    expect_equal(length(data$A6W79$loggers[[1]]$datetime), 49)
    expect_equal(data$A6W79$metadata@tz_type, mc_const_TZ_UTC)
    expect_equal(class(data$A6W79$loggers[[1]]$clean_log), "list")
    expect_equal(length(data$A6W79$loggers[[1]]$sensors), 4)
    expect_equal(data$A6W79$loggers[[1]]$metadata@type, "TMS")
    expect_equal(data$A6W79$loggers[[1]]$metadata@serial_number, "94184102")
    expect_equal(length(data$A2E32$loggers[[1]]$datetime), 75)
    expect_equal(length(data$A2E32$loggers[[1]]$sensors), 4)
    expect_equal(class(data$A2E32$loggers[[1]]$sensors), "list")
    expect_equal(class(data$A2E32$loggers[[1]]$sensors$TMS_T1), "list")
    expect_equal(length(data$A2E32$loggers[[1]]$sensors$TMS_T1), 3)
    expect_equal(length(data$A1E05$loggers[[1]]$datetime), 11)
    expect_equal(length(data$A1E05$loggers[[1]]$sensors), 1)
    expect_true(is.na(data$A1E05$metadata@altitude))
})

test_that("mc_read_from_csv", {
    data <- mc_read_from_csv("data/TOMST/files_table.csv", "data/TOMST/localities_table.csv")
    test_standard_data_format(data)
    expect_equal(data$A1E05$metadata@altitude, 255)
    expect_equal(data$A6W79$metadata@tz_type, mc_const_TZ_USER_DEFINED)
})

test_that("mc_read_TMS_directory", {
    expect_warning(data <- mc_read_directory("data/TOMST", "TOMST"))
    test_standard_data_format(data)
    expect_equal(data[[1]]$metadata@tz_type, mc_const_TZ_UTC)
    expect_equal(length(data), 4)
    expect_equal(length(data[[1]]$loggers), 1)
})
