library(testthat)
library(myClim)
source("test.R")

test_that("mc_agg UTC", {
    data <- mc_read_files("data/clean-datetime_step", "TOMST")
    expect_error(hour_data <- mc_agg(data, "percentile", "hour", use_utc = TRUE, percentiles = c(10, 50, 90), na.rm=TRUE))
    cleaned_data <- mc_prep_clean(data, silent=T)
    expect_warning(hour_data <- mc_agg(cleaned_data, "percentile", "hour", use_utc = TRUE, percentiles = c(10, 50, 90), na.rm=TRUE))
    test_calc_data_format(hour_data)
    expect_equal(length(hour_data$localities[["94184102"]]$sensors), 12)
    calc_data <- mc_agg(cleaned_data)
    test_calc_data_format(calc_data)
    expect_equal(length(calc_data$localities[["94184102"]]$sensors), 4)
    expect_warning(hour2_data <- mc_agg(calc_data, "percentile", "2 hours", use_utc = TRUE, percentiles = c(10, 50, 90), na.rm=TRUE))
    test_calc_data_format(hour2_data)
    expect_equal(length(hour2_data$localities[["94184102"]]$sensors), 12)
})

test_that("mc_agg day functions", {
    data <- mc_read_files("data/agg", "TOMST")
    data <- mc_prep_clean(data, silent=T)
    data <- mc_prep_user_tz(data, list(`91184101`=60))
    agg_data <- mc_agg(data, c("min", "max", "mean", "percentile", "sum", "count", "coverage"), "day", percentiles=50, use_utc=FALSE, na.rm=FALSE)
    test_calc_data_format(agg_data)
    expect_equal(agg_data$localities$`91184101`$sensors$TM_T_min$values, c(NA, 4.125), tolerance = 1e-3)
    expect_equal(agg_data$localities$`91184101`$sensors$TM_T_max$values, c(NA, 11.3125), tolerance = 1e-3)
    expect_equal(agg_data$localities$`91184101`$sensors$TM_T_mean$values, c(NA, 8.434896), tolerance = 1e-3)
    expect_equal(agg_data$localities$`91184101`$sensors$TM_T_percentile50$values, c(NA, 8.4375), tolerance = 1e-3)
    expect_equal(agg_data$localities$`91184101`$sensors$TM_T_sum$values, c(NA, 809.75), tolerance = 1e-3)
    expect_equal(agg_data$localities$`91184101`$sensors$TM_T_count$values, c(87, 96))
    expect_equal(agg_data$localities$`91184101`$sensors$TM_T_coverage$values, c(87/96, 1), tolerance = 1e-3)
    agg_data <- mc_agg(data, c(TM_T=c("min", "max")), "day", use_utc=FALSE, na.rm=TRUE)
    expect_equal(length(agg_data$localities$`91184101`$sensors), 2)
    test_calc_data_format(agg_data)
})

test_that("mc_agg empty data", {
    data <- get_empty_prep_data()
    expect_error(expect_warning(calc_data <- mc_agg(data)))
    data <- mc_read_data("data/TOMST/files_table.csv", "data/TOMST/localities_table.csv")
    data <- mc_prep_clean(data, silent=T)
    expect_error(expect_warning(calc_data <- mc_agg(data, "min", "day", use_utc = TRUE, na.rm=TRUE)))
})

test_that("mc_agg solar aggregation", {
    data <- mc_read_data("data/solar_agg/files_table.csv", "data/solar_agg/localities_table.csv")
    data <- mc_prep_clean(data, silent=T)
    data <- mc_prep_solar_tz(data)
    expect_error(agg_data <- mc_agg(data, c("min", "max"), "hour", use_utc=FALSE, na.rm=FALSE))
    agg_data <- mc_agg(data, c("min", "max"), "day", use_utc=FALSE)
    test_calc_data_format(agg_data)
    expect_equal(length(agg_data$localities$A1E05$sensors), 2)
    test_calc_data_format(agg_data)
})

test_that("mc_agg UTC many NA", {
    data <- mc_read_files("data/clean-datetime_step/data_94184165_0.csv", "TOMST")
    cleaned_data <- mc_prep_clean(data, silent=T)
    expect_warning(agg_data <- mc_agg(cleaned_data, c("min", "max", "mean", "percentile", "sum", "count", "coverage"), "hour", percentiles=50, na.rm=TRUE))
    expect_true(is.na(agg_data$localities[["94184165"]]$sensors$TMS_T1_min$values[[2]]))
    expect_true(is.na(agg_data$localities[["94184165"]]$sensors$TMS_T1_max$values[[2]]))
    expect_true(is.na(agg_data$localities[["94184165"]]$sensors$TMS_T1_mean$values[[2]]))
    expect_true(is.na(agg_data$localities[["94184165"]]$sensors$TMS_T1_percentile50$values[[2]]))
    expect_true(is.na(agg_data$localities[["94184165"]]$sensors$TMS_T1_sum$values[[2]]))
})

test_that("mc_agg long period", {
    data <- mc_read_files("data/agg-month", "TOMST")
    data <- mc_prep_clean(data, silent=T)
    data <- mc_prep_user_tz(data, list(`91184101`=60))
    expect_warning(agg_data <- mc_agg(data, "mean", "week", use_utc=FALSE, na.rm=FALSE))
    test_calc_data_format(agg_data)
    expect_equal(agg_data$metadata@step_text, "week")
    expect_equal(agg_data$localities$`91184101`$datetime[[1]], lubridate::ymd_h("2020-11-02 00"))
    expect_false(is.na(agg_data$metadata@step))
    expect_false(any(is.na(agg_data$localities[["91184101"]]$sensors$TM_T_mean$values)))
    expect_warning(agg_data <- mc_agg(data, "mean", "month", use_utc=FALSE, na.rm=FALSE))
    test_calc_data_format(agg_data)
    expect_equal(agg_data$metadata@step_text, "month")
    expect_true(is.na(agg_data$metadata@step))
})

test_that("mc_agg all period", {
    data <- mc_read_files("data/eco-snow", "TOMST")
    data <- mc_prep_clean(data, silent=T)
    all_data <- mc_agg(data, "mean", "all", na.rm = FALSE)
    test_calc_data_format(all_data)
    expect_equal(all_data$metadata@step_text, "30d 23H 45M 0S")
    expect_equal(length(all_data$localities$`94184102`$datetime), 1)
    expect_equal(length(all_data$localities$`94184103`$datetime), 1)
    expect_false(is.na(all_data$localities$`94184102`$sensors$TMS_T1_mean$values[[1]]))
    expect_true(is.na(all_data$localities$`94184103`$sensors$TMS_T1_mean$values[[1]]))
    all_data <- mc_agg(data, "mean", "all", na.rm = TRUE)
    expect_false(is.na(all_data$localities$`94184102`$sensors$TMS_T1_mean$values[[1]]))
    expect_false(is.na(all_data$localities$`94184103`$sensors$TMS_T1_mean$values[[1]]))
})

test_that("mc_agg agregate from longer to shorter period", {
    data <- mc_read_files("data/eco-snow", "TOMST")
    data <- mc_prep_clean(data, silent=T)
    agg_data <- mc_agg(data, "min", "day", na.rm = TRUE)
    expect_error(mc_agg(agg_data, "min", "hour", na.rm = TRUE))
})

test_that("mc_agg logical sensor", {
    data <- mc_read_files("data/eco-snow/data_94184102_0.csv", "TOMST")
    data <- mc_prep_clean(data, silent=T)
    calc_data <- mc_agg(data)
    calc_data <- mc_calc_snow(calc_data, "TMS_T3")
    expect_warning(month_calc_data <- mc_agg(calc_data, list(snow=c("min", "max", "mean", "percentile", "sum", "count", "coverage")), "week", percentiles = 20))
    expect_equal(month_calc_data$localities$`94184102`$sensors$snow_min$values, c(F, F, F, F))
    expect_equal(month_calc_data$localities$`94184102`$sensors$snow_max$values, c(T, T, T, T))
    expect_equal(month_calc_data$localities$`94184102`$sensors$snow_mean$values, c(F, F, F, T))
    expect_equal(month_calc_data$localities$`94184102`$sensors$snow_percentile20$values, c(F, F, F, F))
    expect_equal(month_calc_data$localities$`94184102`$sensors$snow_sum$values, c(T, T, T, T))
    expect_equal(month_calc_data$localities$`94184102`$sensors$snow_count$values, c(672, 672, 672, 672))
    expect_equal(month_calc_data$localities$`94184102`$sensors$snow_count$metadata@sensor_id, "count")
    expect_equal(month_calc_data$localities$`94184102`$sensors$snow_coverage$values, c(1, 1, 1, 1))
    expect_equal(month_calc_data$localities$`94184102`$sensors$snow_coverage$metadata@sensor_id, "coverage")
})

test_that("mc_agg integer sensor", {
    data <- mc_read_files("data/TOMST/data_94184102_0.csv", "TOMST")
    data <- mc_prep_clean(data, silent=T)
    expect_warning(calc_data <- mc_agg(data, list(TMS_TMSmoisture=c("min", "max", "mean", "percentile", "sum", "count", "coverage")), "hour", percentiles = 10))
    expect_equal(calc_data$localities$`94184102`$sensors$TMS_TMSmoisture_min$values[[1]], 1551)
    expect_equal(calc_data$localities$`94184102`$sensors$TMS_TMSmoisture_max$values[[1]], 1551)
    expect_equal(calc_data$localities$`94184102`$sensors$TMS_TMSmoisture_mean$values[[2]], 1552)
    expect_equal(calc_data$localities$`94184102`$sensors$TMS_TMSmoisture_percentile10$values[[8]], 1549)
    expect_equal(calc_data$localities$`94184102`$sensors$TMS_TMSmoisture_sum$values[[1]], 6204)
    expect_equal(calc_data$localities$`94184102`$sensors$TMS_TMSmoisture_count$values[[1]], 4)
    expect_equal(calc_data$localities$`94184102`$sensors$TMS_TMSmoisture_count$metadata@sensor_id, "count")
    expect_equal(calc_data$localities$`94184102`$sensors$TMS_TMSmoisture_coverage$values[[1]], 1)
    expect_equal(calc_data$localities$`94184102`$sensors$TMS_TMSmoisture_coverage$metadata@sensor_id, "coverage")
})

test_that("mc_agg reaggregate", {
    expect_warning(data <- mc_read_files("data/TOMST/", "TOMST"))
    data <- mc_prep_clean(data, silent=T)
    agg_data <- mc_agg(data)
    agg_all <- mc_agg(agg_data, period = "all", fun = "mean")
    test_calc_data_format(agg_all)
})

