.plot_const_MOISTURE_PHYSICAL <- c("TMS_moisture", "moisture")

#' Plot data from logger
#'
#' Function plot data of one logger
#'
#' @param logger list with informations about logger
#' @param filename output filename
#' @param crop datetime range for plot, not cropping if NA default(c(NA, NA))
#' @export
#' @examples
#' mc_plot_logger(logger, "91184101.png")
mc_plot_logger <- function(logger, filename, crop=c(NA, NA)) {
    png(filename=filename, width=1920, height=1000)
    physical_quantities <- .plot_get_logger_sensors_by_physical(logger)
    .plot_logger_set_parameters(physical_quantities)
    for(physical in physical_quantities){
    }
}

.plot_get_logger_sensors_by_physical <- function(logger) {
    physical <- sapply(logger$sensors, function(x) {
        microclim:::.common_get_sensor_info(logger$metadata, x$metadata)@physical})
    sensor_names <- names(logger$sensors)
    tapply(sensors, physical, c)
}

.plot_logger_set_parameters <-function(physical_quantities)
{
    left_margin <- 4
    top_margin <- 1.5
    right_margin <- 4
    if(length(intersect(.plot_const_MOISTURE_PHYSICAL, names(physical_quantities))) > 0) {
        layout(matrix(1:2))
        bottom_margin <- 0
    }
    else {
        bottom_margin <- 5
    }
    par(mar=c(bottom_margin, left_margin, top_margin, right_margin), mgp=c(2.5,1,0), las=1)
}

.plot_logger_temperature <- function()
{
    plot(logger$datetime, tms$T_A15_cal,type="n",xaxt="n",xlab=NA,ylab="Temperature (°C)",main=sernum,xlim=xlimit,ylim=ylimit)
}

#' Plot data - image
#'
#' Function plot data to file with image function
#'
#' @param data_table data.frame in wideformat generated by mc_reshape_wideformat_interval
#' @param filename output filename
#' @param title of plot
#' @export
#' @examples
#' data_table <- mc_reshape_wideformat_interval(example_tms_data1, sensors="T1")
#' mc_plot_image(data_table, "T1_image.png", "T1 sensor")
mc_plot_image <- function(data_table, filename, title) {
    values_matrix <- as.matrix(data_table[,-1])
    image_height = 50 * ncol(values_matrix) + 100
    if(image_height < 250) {image_height <- 250}
    png(filename = filename,width = 800,height = image_height)
    x_labels <- substr(data_table$datetime[seq(1, nrow(data_table), len=20)], 1, 10)
    bottom_margin <- 7
    left_margin <- 12
    top_margin <- 3
    right_margin <- 8
    par(mar=c(bottom_margin, left_margin, top_margin, right_margin))
    image(values_matrix, xaxt ="n", yaxt="n", col = hcl.colors(12, "viridis", rev = TRUE))
    axis(side = 1, at=seq(0, 1, len=20), labels=x_labels, las=3)
    axis(side = 2, at=seq(0, 1, len=ncol(values_matrix)), labels=colnames(data_table)[-1], las=2)
    legend_values <- round(seq(min(values_matrix, na.rm=T), max(values_matrix, na.rm=T), len=12), 2)
    legend(grconvertX(710, "device"), grconvertY(45, "device"),
           legend_values, fill = hcl.colors(12, "viridis", rev = TRUE), xpd = NA)
    title(main=title, line=0.5, cex.lab=1.2)
    dev.off()
    NULL
}
