#' Plot data
#'
#' Function plot data to file
#'
#' @param data_table data.frame in wideformat generated by mc_reshape_wideformat
#' @param filename output filename
#' @export
mc_plot_image <- function(data_table, filename) {
    png(filename = filename,width = 800,height = 800)
}
